import assert from "node:assert/strict";
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { toolingVersions } from "@stackcanon/tooling-registry";
import {
  applyInitPlan,
  createDoctorReport,
  createInitPlan,
  generateOutputs,
  revertLatestApply,
  syncSources
} from "../src/index.ts";

const repoRoot = path.resolve(import.meta.dirname, "../../..");
const fixturesRoot = path.join(repoRoot, "tests/fixtures");

async function createTempFixtureCopy(fixtureName: string): Promise<string> {
  const sourceRoot = path.join(fixturesRoot, fixtureName);
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), `stackcn-${fixtureName}-`));
  await cp(sourceRoot, tempRoot, { recursive: true });
  return tempRoot;
}

test("doctor reports Nuxt readiness gaps", async () => {
  const report = await createDoctorReport({
    root: path.join(fixturesRoot, "nuxt-basic")
  });

  const messages = report.findings.map((finding) => finding.message);
  const codes = report.findings.map((finding) => finding.code);

  assert.equal(report.schemaVersion, 1);
  assert.equal(report.summary.status, "warning");
  assert.equal(report.context.qualityProviderState, "none");
  assert.equal(report.context.docsSyncState, "none");
  assert.ok(codes.includes("framework_nuxt_config_missing"));
  assert.ok(codes.includes("framework_nuxt_typescript_missing"));
  assert.ok(codes.includes("framework_nuxt_vue_tsc_missing"));
  assert.ok(messages.some((message) => message.includes("Nuxt config is missing")));
  assert.ok(messages.some((message) => message.includes("missing TypeScript tooling")));
  assert.ok(messages.some((message) => message.includes("missing vue-tsc")));
  assert.ok(messages.some((message) => message.includes(`typescript@${toolingVersions.typescript}`)));
  assert.ok(messages.some((message) => message.includes(`vue-tsc@${toolingVersions.vueTsc}`)));
});

test("createInitPlan rejects conflicting Biome and Oxlint providers", async () => {
  await assert.rejects(
    () =>
      createInitPlan({
        root: path.join(fixturesRoot, "biome-oxlint-conflict")
      }),
    /both Biome and Oxlint are installed/
  );
});

test("createInitPlan enables compatibility mode for unsupported TanStack Query majors", async () => {
  const plan = await createInitPlan({
    root: path.join(fixturesRoot, "tanstack-query-unsupported-major"),
    framework: "tanstack-query",
    allowCompat: true
  });

  assert.equal(plan.framework, "tanstack-query");
  assert.equal(plan.manifest.pack?.compatibilityMode, true);
  assert.equal(plan.manifest.pack?.name, "TanStack Query");
});

test("applyInitPlan keeps user-managed Next config untouched", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    const before = await readFile(path.join(tempRoot, "next.config.ts"), "utf8");
    const plan = await createInitPlan({ root: tempRoot });
    const result = await applyInitPlan(plan);
    const after = await readFile(path.join(tempRoot, "next.config.ts"), "utf8");
    const agents = await readFile(path.join(tempRoot, "AGENTS.md"), "utf8");

    assert.equal(before, after);
    assert.ok(result.skippedFiles.includes("next.config.ts"));
    assert.ok(result.writtenFiles.includes("AGENTS.md"));
    assert.match(agents, /generated by stackcn/);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("applyInitPlan patches managed Nuxt config and adds typecheck tooling", async () => {
  const tempRoot = await createTempFixtureCopy("nuxt-managed-config");

  try {
    const plan = await createInitPlan({ root: tempRoot });
    const result = await applyInitPlan(plan);
    const nuxtConfig = await readFile(path.join(tempRoot, "nuxt.config.ts"), "utf8");
    const packageJson = await readFile(path.join(tempRoot, "package.json"), "utf8");

    assert.ok(result.writtenFiles.includes("nuxt.config.ts"));
    assert.match(nuxtConfig, /payloadExtraction: false/);
    assert.match(nuxtConfig, /payloadExtraction: false\s*\n\s*},\n\s*typescript: \{ typeCheck: true \},/);
    assert.match(packageJson, /"typecheck": "nuxt typecheck"/);
    assert.match(packageJson, new RegExp(`"ultracite": "${toolingVersions.ultracite.replace("^", "\\^")}"`));
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("doctor reports TanStack Start alias support gap on Vite 7", async () => {
  const report = await createDoctorReport({
    root: path.join(fixturesRoot, "tanstack-start-basic")
  });

  const messages = report.findings.map((finding) => finding.message);

  assert.ok(messages.some((message) => message.includes(`vite-tsconfig-paths@${toolingVersions.viteTsconfigPaths}`)));
});

test("doctor reports Nest readiness gaps", async () => {
  const report = await createDoctorReport({
    root: path.join(fixturesRoot, "nest-basic")
  });
  const plan = await createInitPlan({
    root: path.join(fixturesRoot, "nest-basic")
  });

  const codes = report.findings.map((finding) => finding.code);
  const messages = report.findings.map((finding) => finding.message);

  assert.ok(codes.includes("framework_pack_validated"));
  assert.ok(codes.includes("framework_nest_config_missing"));
  assert.ok(codes.includes("framework_nest_cli_missing"));
  assert.ok(messages.some((message) => message.includes(`@nestjs/cli@${toolingVersions.nestCli}`)));
  assert.deepEqual(plan.manifest.pack?.focusAreas, ["module boundaries", "controller/service layering", "CLI-driven build flow"]);
  assert.ok(plan.manifest.pack?.reviewChecklist?.includes("Keep controllers thin and avoid embedding business logic in transport handlers."));
});

test("applyInitPlan adds Express backend scripts and TypeScript runtime tooling", async () => {
  const tempRoot = await createTempFixtureCopy("express-basic");

  try {
    const plan = await createInitPlan({ root: tempRoot });
    const result = await applyInitPlan(plan);
    const packageJson = await readFile(path.join(tempRoot, "package.json"), "utf8");

    assert.equal(plan.framework, "express");
    assert.ok(result.writtenFiles.includes("package.json"));
    assert.match(packageJson, new RegExp(`"tsx": "${toolingVersions.tsx.replace("^", "\\^")}"`));
    assert.match(packageJson, new RegExp(`"@types/express": "${toolingVersions.expressTypes.replace("^", "\\^")}"`));
    assert.match(packageJson, /"dev": "tsx watch src\/server.ts"/);
    assert.match(packageJson, /"start": "tsx src\/server.ts"/);
    assert.doesNotMatch(packageJson, /"build": "tsc -p tsconfig.json"/);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("createInitPlan resolves Fastify pack and backend runtime scripts", async () => {
  const plan = await createInitPlan({
    root: path.join(fixturesRoot, "fastify-basic")
  });

  assert.equal(plan.framework, "fastify");
  assert.equal(plan.manifest.pack?.name, "Fastify");
  assert.ok(plan.packageJson.devDependencies.includes(`tsx@${toolingVersions.tsx}`));
  assert.ok(plan.packageJson.scripts.includes("dev=tsx watch src/server.ts"));
  assert.ok(plan.packageJson.scripts.includes("start=tsx src/server.ts"));
});

test("generateOutputs rewrites stackcn-managed AGENTS.md", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    const plan = await createInitPlan({ root: tempRoot });
    await applyInitPlan(plan);
    await writeFile(
      path.join(tempRoot, "AGENTS.md"),
      "<!-- generated by stackcn -->\n# stale agents\n",
      "utf8"
    );

    const result = await generateOutputs({
      root: tempRoot,
      target: "all"
    });
    const agents = await readFile(path.join(tempRoot, "AGENTS.md"), "utf8");
    const aiRulezConfig = await readFile(path.join(tempRoot, ".ai-rulez", "config.yaml"), "utf8");
    const aiRulezAgent = await readFile(path.join(tempRoot, ".ai-rulez", "agents", "stackcanon.md"), "utf8");

    assert.ok(result.writtenFiles.includes("AGENTS.md"));
    assert.ok(result.writtenFiles.includes("CLAUDE.md"));
    assert.ok(result.writtenFiles.includes(".ai-rulez/config.yaml"));
    assert.ok(result.writtenFiles.includes(".ai-rulez/agents/stackcanon.md"));
    assert.deepEqual(result.skippedFiles, []);
    assert.match(agents, /Use the generated ai\/ directory as the single source of truth/);
    assert.match(aiRulezConfig, /version: "3.0"/);
    assert.match(aiRulezAgent, /Framework: next/);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("generateOutputs can invoke ai-rulez with an injected runner", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    const plan = await createInitPlan({ root: tempRoot });
    await applyInitPlan(plan);

    const result = await generateOutputs({
      root: tempRoot,
      target: "ai-rulez",
      runAiRulezGenerate: true,
      aiRulezRunner: async ({ root }) => {
        assert.equal(root, tempRoot);
        await writeFile(path.join(root, ".ai-rulez", "generated.flag"), "ok\n", "utf8");
        return {
          command: "node_modules/.bin/ai-rulez generate"
        };
      }
    });
    const flag = await readFile(path.join(tempRoot, ".ai-rulez", "generated.flag"), "utf8");

    assert.equal(result.aiRulezCommand, "node_modules/.bin/ai-rulez generate");
    assert.ok(result.writtenFiles.includes(".ai-rulez/config.yaml"));
    assert.equal(flag, "ok\n");
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("generateOutputs skips user-managed AGENTS.md", async () => {
  const tempRoot = await createTempFixtureCopy("next-user-managed");

  try {
    const manifestRoot = path.join(tempRoot, ".stackcn");
    const aiRulesRoot = path.join(tempRoot, "ai/rules");
    const aiContextRoot = path.join(tempRoot, "ai/context");

    await mkdir(manifestRoot, { recursive: true });
    await mkdir(aiRulesRoot, { recursive: true });
    await mkdir(aiContextRoot, { recursive: true });
    await writeFile(
      path.join(manifestRoot, "manifest.json"),
      JSON.stringify(
        {
          managedBy: "stackcn",
          framework: "next",
          quality: "ultracite"
        },
        null,
        2
      ),
      "utf8"
    );
    await writeFile(path.join(tempRoot, "ai/config.yaml"), "# generated by stackcn\n", "utf8");
    await writeFile(path.join(aiRulesRoot, "stackcanon-core.md"), "<!-- generated by stackcn -->\n", "utf8");
    await writeFile(path.join(aiContextRoot, "framework.md"), "<!-- generated by stackcn -->\n", "utf8");
    await writeFile(path.join(aiContextRoot, "quality.md"), "<!-- generated by stackcn -->\n", "utf8");

    const before = await readFile(path.join(tempRoot, "AGENTS.md"), "utf8");
    const result = await generateOutputs({
      root: tempRoot,
      target: "agents"
    });
    const after = await readFile(path.join(tempRoot, "AGENTS.md"), "utf8");

    assert.deepEqual(result.writtenFiles, []);
    assert.deepEqual(result.skippedFiles, ["AGENTS.md"]);
    assert.equal(after, before);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("applyInitPlan tracks vendor-init side effects with injected runner", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    const huskyRoot = path.join(tempRoot, ".husky");
    await mkdir(huskyRoot, { recursive: true });
    await writeFile(path.join(huskyRoot, "pre-commit"), "echo before\n", "utf8");

    const plan = await createInitPlan({ root: tempRoot });
    const result = await applyInitPlan(plan, {
      runVendorInit: true,
      vendorInitRunner: async ({ root, plan: vendorPlan }) => {
        assert.equal(vendorPlan.command, "npx");
        assert.deepEqual(vendorPlan.args, ["ultracite", "init"]);
        await mkdir(path.join(root, ".husky"), { recursive: true });
        await mkdir(path.join(root, ".github"), { recursive: true });
        await writeFile(path.join(root, ".husky", "pre-commit"), "npx ultracite fix\n", "utf8");
        await writeFile(path.join(root, ".github", "copilot-instructions.md"), "# generated by vendor\n", "utf8");
        return {
          command: `${vendorPlan.command} ${vendorPlan.args.join(" ")}`
        };
      }
    });

    const huskyHook = await readFile(path.join(tempRoot, ".husky", "pre-commit"), "utf8");
    const backedUpHook = await readFile(
      path.join(tempRoot, result.backupDirectory, ".husky", "pre-commit"),
      "utf8"
    );

    assert.equal(result.vendorInitCommand, "npx ultracite init");
    assert.ok(result.writtenFiles.includes(".husky"));
    assert.ok(result.writtenFiles.includes(".github/copilot-instructions.md"));
    assert.equal(huskyHook, "npx ultracite fix\n");
    assert.equal(backedUpHook, "echo before\n");
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("applyInitPlan tracks install side effects with injected installer", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    await writeFile(path.join(tempRoot, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n", "utf8");
    const plan = await createInitPlan({ root: tempRoot });
    const result = await applyInitPlan(plan, {
      installDependencies: true,
      dependencyInstaller: async ({ root, packageManager }) => {
        assert.equal(packageManager, "pnpm");
        await writeFile(path.join(root, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\npackages:\n  .: {}\n", "utf8");
        return {
          command: "pnpm install"
        };
      }
    });

    const lockfile = await readFile(path.join(tempRoot, "pnpm-lock.yaml"), "utf8");
    const backedUpLockfile = await readFile(
      path.join(tempRoot, result.backupDirectory, "pnpm-lock.yaml"),
      "utf8"
    );

    assert.equal(result.installCommand, "pnpm install");
    assert.ok(result.writtenFiles.includes("pnpm-lock.yaml"));
    assert.equal(backedUpLockfile, "lockfileVersion: '9.0'\n");
    assert.match(lockfile, /packages:/);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("revertLatestApply restores backups and removes generated files", async () => {
  const tempRoot = await createTempFixtureCopy("nuxt-basic");

  try {
    const beforePackageJson = await readFile(path.join(tempRoot, "package.json"), "utf8");
    const plan = await createInitPlan({ root: tempRoot });
    const applyResult = await applyInitPlan(plan);

    assert.ok(applyResult.writtenFiles.includes("AGENTS.md"));

    const revertResult = await revertLatestApply({ root: tempRoot });
    const afterPackageJson = await readFile(path.join(tempRoot, "package.json"), "utf8");

    assert.equal(revertResult.backupDirectory, applyResult.backupDirectory);
    assert.ok(revertResult.restoredPaths.includes("package.json"));
    assert.ok(revertResult.removedPaths.includes("AGENTS.md"));
    assert.ok(revertResult.removedPaths.includes("ai/config.yaml"));
    assert.equal(afterPackageJson, beforePackageJson);
    await assert.rejects(() => readFile(path.join(tempRoot, "AGENTS.md"), "utf8"));
    await assert.rejects(() => readFile(path.join(tempRoot, "ai", "config.yaml"), "utf8"));
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("syncSources writes raw, normalized, and index artifacts from manifest sources", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    const plan = await createInitPlan({ root: tempRoot });
    await applyInitPlan(plan);

    const result = await syncSources({
      root: tempRoot,
      fetchSource: async (source) => ({
        content: `<html><body><h1>${source.title}</h1><p>Canonical content for ${source.id}</p></body></html>`,
        contentType: "text/html; charset=utf-8",
        status: 200
      })
    });
    const normalized = await readFile(
      path.join(tempRoot, ".stackcn", "sources", "normalized", "next-docs.md"),
      "utf8"
    );
    const index = await readFile(path.join(tempRoot, result.indexPath), "utf8");

    assert.equal(result.syncedSources.length, 2);
    assert.ok(result.syncedSources.some((source) => source.id === "next-docs"));
    assert.match(normalized, /Canonical content for next-docs/);
    assert.match(index, /next-ai-agents/);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});

test("doctor reports docs sync state before and after sync", async () => {
  const tempRoot = await createTempFixtureCopy("next-basic");

  try {
    const plan = await createInitPlan({ root: tempRoot });
    await applyInitPlan(plan);

    const beforeSync = await createDoctorReport({ root: tempRoot });
    assert.equal(beforeSync.context.docsSyncState, "missing");
    assert.ok(beforeSync.findings.some((finding) => finding.code === "docs_sync_missing"));

    await syncSources({
      root: tempRoot,
      fetchSource: async (source) => ({
        content: `# ${source.title}\n\nUp to date.`,
        contentType: "text/markdown; charset=utf-8",
        status: 200
      })
    });

    const afterSync = await createDoctorReport({ root: tempRoot });
    assert.equal(afterSync.context.docsSyncState, "ready");
    assert.ok(afterSync.findings.some((finding) => finding.code === "docs_sync_ready"));
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
});
