import { biomeSchemaUrls } from "@stackcanon/tooling-registry";

export interface AiOutputTarget {
  readonly name: string;
  readonly command: readonly string[];
}

export interface AiEnginePlan {
  readonly sourceDirectory: string;
  readonly targets: readonly AiOutputTarget[];
}

export interface AiConfigInput {
  readonly projectName: string;
}

export interface PackContextInput {
  readonly focusAreas?: readonly string[];
  readonly reviewChecklist?: readonly string[];
  readonly name?: string;
  readonly versionRange?: string;
  readonly lastReviewed?: string;
  readonly sources?: readonly string[];
  readonly summary?: string;
  readonly guidance?: readonly string[];
  readonly compatibilityMode?: boolean;
}

export interface FrameworkContextInput {
  readonly framework: string;
  readonly pack?: PackContextInput;
}

export interface AgentsDocumentInput {
  readonly framework: string;
  readonly quality: string;
  readonly pack?: PackContextInput;
  readonly contextFiles: readonly string[];
}

export const STACKCN_MANAGED_MARKER = "generated by stackcn";

export const defaultAiTargets: readonly AiOutputTarget[] = [
  {
    name: "agents",
    command: ["stackcn", "generate", "--target", "agents"]
  },
  {
    name: "ai-rulez",
    command: ["stackcn", "generate", "--target", "ai-rulez"]
  },
  {
    name: "claude",
    command: ["stackcn", "generate", "--target", "claude"]
  }
];

export function createAiEnginePlan(sourceDirectory: string): AiEnginePlan {
  return {
    sourceDirectory,
    targets: defaultAiTargets
  };
}

export function isStackcnManagedContent(content: string): boolean {
  return (
    content.includes(STACKCN_MANAGED_MARKER) ||
    content.includes('"managedBy":"stackcn"') ||
    content.includes('"managedBy": "stackcn"')
  );
}

export function renderAiConfig(input: AiConfigInput): string {
  return `# ${STACKCN_MANAGED_MARKER}
version: 1
project: "${input.projectName}"
source_of_truth: "ai/"
targets:
  - agents
  - ai-rulez
  - claude
`;
}

export function renderCoreRulesMarkdown(framework: string, quality: string, compatibilityMode = false): string {
  return `<!-- ${STACKCN_MANAGED_MARKER} -->
---
priority: high
---

# StackCanon Core Rules

- Follow the validated ${framework} pack before relying on model memory.
- Respect the selected quality provider: ${quality}.
- Prefer safe, reversible changes over aggressive rewrites.
- If a file is user-managed, inspect it before editing.
${compatibilityMode ? "- Compatibility mode is active, so confirm behavior against the closest validated major before changing architecture." : ""}
`;
}

export function renderFrameworkContextMarkdown(input: FrameworkContextInput): string {
  const lines = [
    `<!-- ${STACKCN_MANAGED_MARKER} -->`,
    "---",
    "priority: medium",
    "---",
    "",
    "# Framework Context",
    "",
    `Resolved framework: ${input.framework}`
  ];

  if (input.pack?.name) {
    lines.push(`Validated pack: ${input.pack.name}`);
  } else {
    lines.push("Validated pack: not available yet");
  }

  if (input.pack?.versionRange) {
    lines.push(`Supported range: ${input.pack.versionRange}`);
  }

  if (input.pack?.lastReviewed) {
    lines.push(`Last reviewed: ${input.pack.lastReviewed}`);
  }

  if (input.pack?.compatibilityMode) {
    lines.push("Compatibility mode: enabled");
  }

  if (input.pack?.summary) {
    lines.push("", input.pack.summary);
  }

  if (input.pack?.guidance?.length) {
    lines.push("", "## Guidance", ...input.pack.guidance.map((entry) => `- ${entry}`));
  }

  if (input.pack?.focusAreas?.length) {
    lines.push("", "## Focus Areas", ...input.pack.focusAreas.map((entry) => `- ${entry}`));
  }

  if (input.pack?.reviewChecklist?.length) {
    lines.push("", "## Review Checklist", ...input.pack.reviewChecklist.map((entry) => `- ${entry}`));
  }

  if (input.pack?.sources?.length) {
    lines.push("", "## Sources", ...input.pack.sources.map((source) => `- ${source}`));
  }

  lines.push("", "Use this file as the first project-specific framework context before consulting external docs.");

  return `${lines.join("\n")}\n`;
}

function getQualityGuidance(quality: string): readonly string[] {
  switch (quality) {
    case "ultracite":
      return [
        "Prefer Ultracite's own init and migration flow before hand-editing downstream provider config.",
        "Treat Biome or Oxlint integration as vendor-managed unless StackCanon generated the file."
      ];
    case "biome":
      return [
        "Keep Biome as the single formatter and linter baseline unless the repo explicitly opts out.",
        "Only patch existing Biome config automatically when it is stackcn-managed."
      ];
    case "oxlint":
      return [
        "Use Oxlint as the single lint baseline and avoid parallel Biome lint ownership.",
        "Only patch existing Oxlint config automatically when it is stackcn-managed."
      ];
    default:
      return ["No quality provider was selected. Avoid generating tool-specific config until one is chosen."];
  }
}

export function renderQualityContextMarkdown(quality: string): string {
  const lines = [
    `<!-- ${STACKCN_MANAGED_MARKER} -->`,
    "---",
    "priority: medium",
    "---",
    "",
    "# Quality Context",
    "",
    `Selected quality provider: ${quality}`,
    "",
    ...getQualityGuidance(quality).map((entry) => `- ${entry}`)
  ];

  return `${lines.join("\n")}\n`;
}

function appendPackDetails(lines: string[], pack: PackContextInput | undefined): void {
  if (!pack?.name) {
    return;
  }

  lines.push(`- Validated pack: ${pack.name}`);

  if (pack.versionRange) {
    lines.push(`- Supported range: ${pack.versionRange}`);
  }

  if (pack.compatibilityMode) {
    lines.push("- Compatibility mode: enabled");
  }

  if (pack.focusAreas?.length) {
    lines.push(`- Focus areas: ${pack.focusAreas.join(", ")}`);
  }
}

export interface AiRulezConfigInput {
  readonly projectName: string;
}

export function renderAiRulezConfig(input: AiRulezConfigInput): string {
  return `# ${STACKCN_MANAGED_MARKER}
version: "3.0"
name: "${input.projectName}"

presets:
  - claude
  - codex
`;
}

export function renderAgentsDocument(input: AgentsDocumentInput): string {
  const lines = [
    `<!-- ${STACKCN_MANAGED_MARKER} -->`,
    "# AGENTS.md",
    "",
    "## Core Instruction",
    "Use the generated ai/ directory as the single source of truth for project-specific AI guidance.",
    "",
    "## Current Setup",
    `- Framework: ${input.framework}`,
    `- Quality provider: ${input.quality}`
  ];

  appendPackDetails(lines, input.pack);

  lines.push(
    "",
    "## Read Before Coding",
    ...input.contextFiles.map((contextFile) => `- ${contextFile}`),
    "",
    "Only read the sections relevant to the current task before making changes."
  );

  return `${lines.join("\n")}\n`;
}

export function renderClaudeDocument(input: AgentsDocumentInput): string {
  const lines = [
    `<!-- ${STACKCN_MANAGED_MARKER} -->`,
    "# CLAUDE.md",
    "",
    "Use `ai/` as the canonical project context before making changes.",
    "",
    "## Current Setup",
    `- Framework: ${input.framework}`,
    `- Quality provider: ${input.quality}`
  ];

  appendPackDetails(lines, input.pack);

  lines.push(
    "",
    "## Read First",
    ...input.contextFiles.map((contextFile) => `- ${contextFile}`),
    "",
    "Prefer the generated project context over model memory."
  );

  return `${lines.join("\n")}\n`;
}

export function renderBiomeConfig(): string {
  return `{
  "//": "${STACKCN_MANAGED_MARKER}",
  "$schema": "${biomeSchemaUrls.v2}",
  "formatter": {
    "enabled": true,
    "indentStyle": "space"
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "double",
      "semicolons": "always"
    }
  },
  "files": {
    "ignoreUnknown": true
  }
}
`;
}

export function renderOxlintConfig(): string {
  return `{
  "//": "${STACKCN_MANAGED_MARKER}",
  "rules": {}
}
`;
}

export function renderVsCodeSettings(quality: string): string {
  const action = quality === "oxlint" ? `"source.fixAll.oxlint": "explicit"` : `"source.fixAll.biome": "explicit"`;

  return `// ${STACKCN_MANAGED_MARKER}
{
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    ${action}
  }
}
`;
}

export function renderNextConfig(): string {
  return `// ${STACKCN_MANAGED_MARKER}
const nextConfig = {
  reactStrictMode: true
};

export default nextConfig;
`;
}

export function renderViteConfig(framework: string): string {
  return `// ${STACKCN_MANAGED_MARKER}
import { defineConfig } from "vite";

export default defineConfig({
  clearScreen: false,
  define: {
    __STACKCANON_FRAMEWORK__: ${JSON.stringify(framework)}
  }
});
`;
}
